export default {
  SET_USERS: 'SET_USERS',
  CHANGE_USER_OBJECT: 'CHANGE_USER_OBJECT',
  SET_USER_GROUPS: 'SET_USER_GROUPS',
  SET_ACTIVE_GROUP: 'SET_ACTIVE_GROUP',
  ADD_HISTORY_TO_GROUP: 'ADD_HISTORY_TO_GROUP',
  ADD_GROUP: 'ADD_GROUP',
  ADD_TO_CONVERSATION_MAP: 'ADD_TO_CONVERSATION_MAP',
  CLEAR_FROM_CONVERSATION_MAP: 'CLEAR_FROM_CONVERSATION_MAP',
  ADD_USER: 'ADD_USER'
}
